name: Update Data

on:
  schedule:
    - cron: '0 0 * * *'  # Se ejecuta a la medianoche

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.2'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data collector
        run: |
          python src/proyecto/static/models/collector.py 
