name: Update Data

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      log_level:
        description: 'Nivel de registro a usar'
        required: false
        default: 'INFO'
      force_update:
        description: 'Forzar la actualización de datos (true/false)'
        required: false
        default: 'false'

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.2'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run data collector
        run: |
          echo "Nivel de registro: ${{ github.event.inputs.log_level }}"
          echo "Forzar actualización: ${{ github.event.inputs.force_update }}"
          python src/proyecto/static/models/collector.py
            --log-level ${{ github.event.inputs.log_level }}
            --force ${{ github.event.inputs.force_update }}
